[package]
name = "market_data"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
deribit-http = { workspace = true }
tracing = { workspace = true }
tokio = { workspace = true }
tracing-subscriber = { workspace = true }