[package]
name = "private"
version = "0.1.0"
edition = "2024"


[dependencies]
deribit-http = { workspace = true }
tracing = { workspace = true }
tokio = { workspace = true }
dotenv = { workspace = true }
chrono = { workspace = true }