name: Build

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - main
      - 'release/**'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ${{ matrix.os }}
    container: ${{ matrix.container }}
    
    strategy:
      matrix:
        include:
          - os: ubuntu-22.04
          - os: ubuntu-latest


    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Install dependencies
        run: |
          if [ "${{ matrix.container }}" = "archlinux:latest" ]; then
            pacman -Syu --noconfirm make fontconfig pkgconf gcc
          elif [ "${{ runner.os }}" = "Linux" ]; then
            sudo apt-get update && sudo apt-get install -y make libfontconfig1-dev pkg-config build-essential
          elif [ "${{ runner.os }}" = "macOS" ]; then
            brew install make fontconfig pkg-config gcc
          fi

      - name: Build
        run: make build